server:
  port: 7002

#Eureka 配置
eureka:
  instance:
    hostname: www.eureka7002.com #Eureka 服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向Eureka注册中心注册自己（Eureka服务器本身不需要注册自己）
    fetch-registry: false # false表示自己为注册中心
    service-url: #监控页面(http://localhost:7001/),注册的时候才加上 eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://www.eureka7001.com:7001/eureka/,http://www.eureka7003.com:7003/eureka/